---
- name: Test1
  hosts: deployment
  gather_facts: F
  tasks:
  - name: show shell info
    shell: echo "{{ item }}"
    with_items:  groups['compute']
    register: echo
  - name: show debug info
    debug: msg="host is {{ item }}"
    with_items:  groups['compute']
  # show all the hosts in the inventory
  - debug:
    msg: "{{ item }}"
    loop: "{{ groups['all'] }}"

  # show all the hosts in the current play
  - debug:
    msg: "{{ item }}"
    loop: "{{ ansible_play_batch }}"
